image: node:8

before_script:
  - npm install

cache:
  paths:
    - node_modules/

# test:lint:
#   script:
#     - npm run lint

test:vulnerabilities:
  script:
    - npm run vuln-test

test:node:8:
  script:
    - npm install -g codecov
    - npm test && codecov

test:node:6:
  image: node:6
  script:
    - npm test

test:node:7:
  image: node:7
  script:
    - npm test

test:node:4:
  image: node:4
  script:
    - npm test

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish