/**
 * Intellidrone API
 * This ios Intellidrone API designed by [Singleton](http://singleton.com.ar).You  can find out more about Swagger at [Singleton Web Page](http://singleton.com.ar) or on [Intellidrone Web Page](http://robotagro.com).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@singleton.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.intellidrone_api_client_js);
  }
}(this, function(expect, intellidrone_api_client_js) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new intellidrone_api_client_js.Actividades();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  };

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  };

  describe('Actividades', function() {
    it('should create an instance of Actividades', function() {
      // uncomment below and update the code to test Actividades
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be.a(intellidrone_api_client_js.Actividades);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property sampleDate (base name: "sampleDate")', function() {
      // uncomment below and update the code to test the property sampleDate
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property latitude (base name: "latitude")', function() {
      // uncomment below and update the code to test the property latitude
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property longitude (base name: "longitude")', function() {
      // uncomment below and update the code to test the property longitude
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property vacaId (base name: "vaca_id")', function() {
      // uncomment below and update the code to test the property vacaId
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property vaca (base name: "vaca")', function() {
      // uncomment below and update the code to test the property vaca
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property insertDate (base name: "insertDate")', function() {
      // uncomment below and update the code to test the property insertDate
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property colectionDate (base name: "colectionDate")', function() {
      // uncomment below and update the code to test the property colectionDate
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property hdop (base name: "hdop")', function() {
      // uncomment below and update the code to test the property hdop
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property satellites (base name: "satellites")', function() {
      // uncomment below and update the code to test the property satellites
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property signal (base name: "signal")', function() {
      // uncomment below and update the code to test the property signal
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property voltage (base name: "voltage")', function() {
      // uncomment below and update the code to test the property voltage
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

    it('should have the property connectionsAttempts (base name: "connectionsAttempts")', function() {
      // uncomment below and update the code to test the property connectionsAttempts
      // var instance = new intellidrone_api_client_js.Actividades();
      // expect(instance).to.be();
    });

  });

}));
