/**
 * Intellidrone API
 * This ios Intellidrone API designed by [Singleton](http://singleton.com.ar).You  can find out more about Swagger at [Singleton Web Page](http://singleton.com.ar) or on [Intellidrone Web Page](http://robotagro.com).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@singleton.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['/ApiClient', '/models/Vacas'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Vacas'));
  } else {
    // Browser globals (root is window)
    if (!root.intellidrone_api_client_js) {
      root.intellidrone_api_client_js = {};
    }
    root.intellidrone_api_client_js.Actividades = factory(root.intellidrone_api_client_js.ApiClient, root.intellidrone_api_client_js.Vacas);
  }
}(this, function(ApiClient, Vacas) {
  'use strict';


  /**
   * The Actividades model module.
   * @module /models/Actividades
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Actividades</code>.
   * @alias module:/models/Actividades
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Actividades</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:/models/Actividades} obj Optional instance to populate.
   * @return {module:/models/Actividades} The populated <code>Actividades</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('sampleDate')) {
        obj['sampleDate'] = ApiClient.convertToType(data['sampleDate'], 'Date');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
      }
      if (data.hasOwnProperty('vaca_id')) {
        obj['vaca_id'] = ApiClient.convertToType(data['vaca_id'], 'String');
      }
      if (data.hasOwnProperty('vaca')) {
        obj['vaca'] = Vacas.constructFromObject(data['vaca']);
      }
      if (data.hasOwnProperty('insertDate')) {
        obj['insertDate'] = ApiClient.convertToType(data['insertDate'], 'Date');
      }
      if (data.hasOwnProperty('colectionDate')) {
        obj['colectionDate'] = ApiClient.convertToType(data['colectionDate'], 'Date');
      }
      if (data.hasOwnProperty('hdop')) {
        obj['hdop'] = ApiClient.convertToType(data['hdop'], 'Number');
      }
      if (data.hasOwnProperty('satellites')) {
        obj['satellites'] = ApiClient.convertToType(data['satellites'], 'Number');
      }
      if (data.hasOwnProperty('signal')) {
        obj['signal'] = ApiClient.convertToType(data['signal'], 'Number');
      }
      if (data.hasOwnProperty('voltage')) {
        obj['voltage'] = ApiClient.convertToType(data['voltage'], 'Number');
      }
      if (data.hasOwnProperty('tag')) {
        obj['tag'] = ApiClient.convertToType(data['tag'], 'String');
      }
      if (data.hasOwnProperty('connectionsAttempts')) {
        obj['connectionsAttempts'] = ApiClient.convertToType(data['connectionsAttempts'], 'Number');
      }
    }
    return obj;
  };

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {Date} sampleDate
   */
  exports.prototype['sampleDate'] = undefined;
  /**
   * @member {Number} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {Number} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {String} vaca_id
   */
  exports.prototype['vaca_id'] = undefined;
  /**
   * @member {module:models/Vacas} vaca
   */
  exports.prototype['vaca'] = undefined;
  /**
   * @member {Date} insertDate
   */
  exports.prototype['insertDate'] = undefined;
  /**
   * @member {Date} colectionDate
   */
  exports.prototype['colectionDate'] = undefined;
  /**
   * @member {Number} hdop
   */
  exports.prototype['hdop'] = undefined;
  /**
   * @member {Number} satellites
   */
  exports.prototype['satellites'] = undefined;
  /**
   * @member {Number} signal
   */
  exports.prototype['signal'] = undefined;
  /**
   * @member {Number} voltage
   */
  exports.prototype['voltage'] = undefined;
  /**
   * @member {String} tag
   */
  exports.prototype['tag'] = undefined;
  /**
   * @member {Number} connectionsAttempts
   */
  exports.prototype['connectionsAttempts'] = undefined;


  return exports;
}));


