/**
 * Intellidrone API
 * This ios Intellidrone API designed by [Singleton](http://singleton.com.ar).You  can find out more about Swagger at [Singleton Web Page](http://singleton.com.ar) or on [Intellidrone Web Page](http://robotagro.com).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@singleton.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['/ApiClient', '/models/Linea', '/models/Vacas'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Linea'), require('./Vacas'));
  } else {
    // Browser globals (root is window)
    if (!root.intellidrone_api_client_js) {
      root.intellidrone_api_client_js = {};
    }
    root.intellidrone_api_client_js.UploadResponse = factory(root.intellidrone_api_client_js.ApiClient, root.intellidrone_api_client_js.Linea, root.intellidrone_api_client_js.Vacas);
  }
}(this, function(ApiClient, Linea, Vacas) {
  'use strict';


  /**
   * The UploadResponse model module.
   * @module /models/UploadResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UploadResponse</code>.
   * @alias module:/models/UploadResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>UploadResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:/models/UploadResponse} obj Optional instance to populate.
   * @return {module:/models/UploadResponse} The populated <code>UploadResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('actividades_insertadas')) {
        obj['actividades_insertadas'] = ApiClient.convertToType(data['actividades_insertadas'], 'Number');
      }
      if (data.hasOwnProperty('nuevas_vacas')) {
        obj['nuevas_vacas'] = ApiClient.convertToType(data['nuevas_vacas'], [Vacas]);
      }
      if (data.hasOwnProperty('lineas_con_error')) {
        obj['lineas_con_error'] = ApiClient.convertToType(data['lineas_con_error'], [Linea]);
      }
    }
    return obj;
  };

  /**
   * @member {Number} actividades_insertadas
   */
  exports.prototype['actividades_insertadas'] = undefined;
  /**
   * @member {Array.<module:models/Vacas>} nuevas_vacas
   */
  exports.prototype['nuevas_vacas'] = undefined;
  /**
   * @member {Array.<module:models/Linea>} lineas_con_error
   */
  exports.prototype['lineas_con_error'] = undefined;


  return exports;
}));


