/**
 * Intellidrone API
 * This ios Intellidrone API designed by [Singleton](http://singleton.com.ar).You  can find out more about Swagger at [Singleton Web Page](http://singleton.com.ar) or on [Intellidrone Web Page](http://robotagro.com).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@singleton.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['/ApiClient', '/models/Actividades', '/models/Lotes'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Actividades'), require('./Lotes'));
  } else {
    // Browser globals (root is window)
    if (!root.intellidrone_api_client_js) {
      root.intellidrone_api_client_js = {};
    }
    root.intellidrone_api_client_js.Vacas = factory(root.intellidrone_api_client_js.ApiClient, root.intellidrone_api_client_js.Actividades, root.intellidrone_api_client_js.Lotes);
  }
}(this, function(ApiClient, Actividades, Lotes) {
  'use strict';


  /**
   * The Vacas model module.
   * @module /models/Vacas
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Vacas</code>.
   * @alias module:/models/Vacas
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>Vacas</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:/models/Vacas} obj Optional instance to populate.
   * @return {module:/models/Vacas} The populated <code>Vacas</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('sex')) {
        obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
      }
      if (data.hasOwnProperty('months')) {
        obj['months'] = ApiClient.convertToType(data['months'], 'Number');
      }
      if (data.hasOwnProperty('weight')) {
        obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
      }
      if (data.hasOwnProperty('location_id')) {
        obj['location_id'] = ApiClient.convertToType(data['location_id'], 'String');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = Lotes.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('actividades')) {
        obj['actividades'] = ApiClient.convertToType(data['actividades'], [Actividades]);
      }
    }
    return obj;
  };

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:models/Vacas.SexEnum} sex
   */
  exports.prototype['sex'] = undefined;
  /**
   * @member {Number} months
   */
  exports.prototype['months'] = undefined;
  /**
   * @member {Number} weight
   */
  exports.prototype['weight'] = undefined;
  /**
   * @member {String} location_id
   */
  exports.prototype['location_id'] = undefined;
  /**
   * @member {module:models/Lotes} location
   */
  exports.prototype['location'] = undefined;
  /**
   * @member {Array.<module:models/Actividades>} actividades
   */
  exports.prototype['actividades'] = undefined;


  /**
   * Allowed values for the <code>sex</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SexEnum = {
    /**
     * value: "Hembra"
     * @const
     */
    Hembra: 'Hembra',
    /**
     * value: "Macho"
     * @const
     */
    Macho: 'Macho' };


  return exports;
}));


