/**
 * Intellidrone API
 * This ios Intellidrone API designed by [Singleton](http://singleton.com.ar).You  can find out more about Swagger at [Singleton Web Page](http://singleton.com.ar) or on [Intellidrone Web Page](http://robotagro.com).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@singleton.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['/ApiClient', '/models/Actividades', '/models/DeletedResponse', '/models/Error', '/models/Linea', '/models/Lotes', '/models/UploadResponse', '/models/Users', '/models/Vacas', '/api/ActividadesApi', '/api/LotesApi', '/api/UsersApi', '/api/VacasApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./models/Actividades'), require('./models/DeletedResponse'), require('./models/Error'), require('./models/Linea'), require('./models/Lotes'), require('./models/UploadResponse'), require('./models/Users'), require('./models/Vacas'), require('./api/ActividadesApi'), require('./api/LotesApi'), require('./api/UsersApi'), require('./api/VacasApi'));
  }
}(function(ApiClient, Actividades, DeletedResponse, Error, Linea, Lotes, UploadResponse, Users, Vacas, ActividadesApi, LotesApi, UsersApi, VacasApi) {
  'use strict';

  /**
   * This_ios_Intellidrone_API_designed_by__Singleton_httpsingleton_com_ar_You__can_find_out_more_about_Swagger_at__Singleton_Web_Page_httpsingleton_com_ar_or_on__Intellidrone_Web_Page_httprobotagro_com_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var intellidrone_api_client_js = require('/index'); // See note below*.
   * var xxxSvc = new intellidrone_api_client_js.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new intellidrone_api_client_js.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['/index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new intellidrone_api_client_js.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new intellidrone_api_client_js.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module /index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:/ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Actividades model constructor.
     * @property {module:/models/Actividades}
     */
    Actividades: Actividades,
    /**
     * The DeletedResponse model constructor.
     * @property {module:/models/DeletedResponse}
     */
    DeletedResponse: DeletedResponse,
    /**
     * The Error model constructor.
     * @property {module:/models/Error}
     */
    Error: Error,
    /**
     * The Linea model constructor.
     * @property {module:/models/Linea}
     */
    Linea: Linea,
    /**
     * The Lotes model constructor.
     * @property {module:/models/Lotes}
     */
    Lotes: Lotes,
    /**
     * The UploadResponse model constructor.
     * @property {module:/models/UploadResponse}
     */
    UploadResponse: UploadResponse,
    /**
     * The Users model constructor.
     * @property {module:/models/Users}
     */
    Users: Users,
    /**
     * The Vacas model constructor.
     * @property {module:/models/Vacas}
     */
    Vacas: Vacas,
    /**
     * The ActividadesApi service constructor.
     * @property {module:/api/ActividadesApi}
     */
    ActividadesApi: ActividadesApi,
    /**
     * The LotesApi service constructor.
     * @property {module:/api/LotesApi}
     */
    LotesApi: LotesApi,
    /**
     * The UsersApi service constructor.
     * @property {module:/api/UsersApi}
     */
    UsersApi: UsersApi,
    /**
     * The VacasApi service constructor.
     * @property {module:/api/VacasApi}
     */
    VacasApi: VacasApi,
  };

  return exports;
}));
