/**
 * Intellidrone API
 * This ios Intellidrone API designed by [Singleton](http://singleton.com.ar).You  can find out more about Swagger at [Singleton Web Page](http://singleton.com.ar) or on [Intellidrone Web Page](http://robotagro.com).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@singleton.com.ar
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.intellidrone_api_client_js);
  }
}(this, function(expect, intellidrone_api_client_js) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new intellidrone_api_client_js.ActividadesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  };

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  };

  describe('ActividadesApi', function() {
    describe('addActividad', function() {
      it('should call addActividad successfully', function(done) {
        // uncomment below and update the code to test addActividad
        // instance.addActividad(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done();
      });
    });
    describe('addActividades', function() {
      it('should call addActividades successfully', function(done) {
        // uncomment below and update the code to test addActividades
        // instance.addActividades(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done();
      });
    });
    describe('deleteActividad', function() {
      it('should call deleteActividad successfully', function(done) {
        // uncomment below and update the code to test deleteActividad
        // instance.deleteActividad(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done();
      });
    });
    describe('editActividad', function() {
      it('should call editActividad successfully', function(done) {
        // uncomment below and update the code to test editActividad
        // instance.editActividad(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done();
      });
    });
    describe('getActividadById', function() {
      it('should call getActividadById successfully', function(done) {
        // uncomment below and update the code to test getActividadById
        // instance.getActividadById(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done();
      });
    });
    describe('getActividades', function() {
      it('should call getActividades successfully', function(done) {
        // uncomment below and update the code to test getActividades
        // instance.getActividades(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done();
      });
    });
  });

}));
